[monster]
name = "Demon Vulgar"
index = 1
level = 1
range = 20
physical_attack = 200
defense = 10
agressive = true
sight = 240
experience = 2

[[drop]]
index = 20
prefix = 0
chance = 10.0
quest = 13

[[spawn]]
bottom_x = 257800
bottom_y = 259904
top_x = 258129
top_y = 260045
quantity = 30