[[item]]
name = "Small Medicine" 
index = 47 
image = "item002"
description = "Recovers health points by 100"
consumable = true
stackable = false
cooldown_in_seconds = 1.3
category = "medicine"
health_recovered = 100

[[item]]
name = "Medium Medicine" 
index = 48
image = "item002"
description = "Recovers health points by 300"
consumable = true
stackable = false
cooldown_in_seconds = 1.3
category = "medicine"
health_recovered = 300